### ISSUE TITLE
mobile cut-off

### ISSUE THREAD

**Issue by theotheroracle** [mijorus/smile#11]
the window is cutoff on mobile, as it's not able to be resized

**Comment by mijorus** [comment]
@theotheroracle mobile? like a pinephone or something?

**Comment by theotheroracle** [comment]
yeah pinephone

**Comment by mijorus** [comment]
@theotheroracle ok, I'll try to improve the mobile compatibility

**Comment by mijorus** [comment]
@theotheroracle version 1.5.7 will soon be available on flathub, which allows the window to be resized freely.

Can you please tell me if that helps in some way?
Thanks

**Comment by theotheroracle** [comment]
yea that works for me ^•^
