### ISSUE TITLE
Won't use dark theme

### ISSUE THREAD

**Issue by tobealive** [mijorus/smile#17]
I'm dying without dark theme. Can't make it work :/ 

currently on pop os

**Comment by tobealive** [comment]
Okay building from source instead of installing from flathub saved me ❤

**Comment by mijorus** [comment]
The app does not force any theme, should follow the GTK theme set on flatpak.

Btw I am on PopOS too, but never encountered this problem. Are you using extensions / scripts to change your desktop theme from light to dark?

**Comment by proninyaroslav** [comment]
Flatpak & freedesktop have added a dbus item for [checking dark mode preference.](https://github.com/flatpak/xdg-desktop-portal/blob/d7a304a00697d7d608821253cd013f3b97ac0fb6/data/org.freedesktop.impl.portal.Settings.xml#L33-L45)

[Spec](https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.Settings):

    Portal API Reference

    Portal interfaces are available to sandboxed applications with the default filtered session bus access of Flatpak. Unless otherwise specified, they appear under the bus name org.freedesktop.portal.Desktop and the object path /org/freedesktop/portal/desktop on the session bus.

    This interface provides read-only access to a small number of host settings required for toolkits similar to XSettings. It is not for general purpose settings.

    Currently the interface provides the following keys:

    org.freedesktop.appearance color-scheme u

    Indicates the system's preferred color scheme. Supported values are:
    0: No preference
    1: Prefer dark appearance
    2: Prefer light appearance

    Unknown values should be treated as 0 (no preference).

Can be checked from terminal with:

```
dbus-send --print-reply --dest=org.freedesktop.portal.Desktop /org/freedesktop/portal/desktop org.freedesktop.portal.Settings.Read string:'org.freedesktop.appearance' string:'color-scheme'
```

**Comment by VarLad** [comment]
@mijorus I can report the same problem on Fedora 36 GNOME 42

**Comment by tobealive** [comment]
Got it somehow working after some experimentation and have not had any more issues since then. Unfortunately I don't remember exactly what I did then. So I'm feeling a bit guilty of not coming back and providing a proper reproduction. It's definitely built from source and I think it was working on integrating GTK themes into flatpak that solved it. The good news is that it's definitely possible on the user side.

**Comment by mijorus** [comment]
Sorry guys but I've been busy lately; I'm looking into this issue now
