### ISSUE TITLE
Support for localization

### ISSUE THREAD

**Issue by proninyaroslav** [mijorus/smile#18]
It's a good idea to support localization, including localization of standard tags from a JSON file so that the user can search emoji in your own language.

**Comment by mijorus** [comment]
definitely, it is probably the next thing I need to work on!

**Comment by mijorus** [comment]
WIP at https://github.com/mijorus/smile/tree/localized-tags

**Comment by proninyaroslav** [comment]
@mijorus 
Cool, let me know when it's ready to accept localization files

**Comment by mijorus** [comment]
> @mijorus 
> Cool, let me know when it's ready to accept localization files

I am using some pre-made tags from emojibase, released under the MIT license.
While suggestions are always welcome, I have a good database to start from

**Comment by mijorus** [comment]
Available since 1.7.0
