### ISSUE TITLE
Copy not working anymore

### ISSUE THREAD

**Issue by RichardFevrier** [mijorus/smile#27]
Hi, with previous version of `Smile` I was able to `copy` with left mouse click but it is not working anymore.
I did check the logs with `flatpak run it.mijorus.smile` but nothing appears suspicious.

Version `2.0.2`
Origin `Flathub`
OS `Fedora Silverblue 37`

**Comment by mijorus** [comment]
Hi @RichardFevrier , I've been using version 2 for a while now and copy with mouse-click works just fine for me.

What mouse are you using?
Wayland or X11 ? I'm assuming Wayland

**Comment by RichardFevrier** [comment]
Hi @mijorus thanks for the super fast answer !
Yes Wayland

**Comment by mijorus** [comment]
I'm downloading an ISO for silverblue RN, I'm guessing there are some sort of limitations there.

I've tested on multiple systems and found no issues so far

**Comment by RichardFevrier** [comment]
Just did `sudo flatpak update --commit=a8cfc8db5367a1c7f01c0f7a31fef094f2892c8c2f65f4fee2a6b10b4f457391 it.mijorus.smile` and it's perfectly working

**Comment by mijorus** [comment]
ok wait, please wait a second, which version is that?

**Comment by RichardFevrier** [comment]
An old one =) you could see it from `flatpak remote-info --log flathub it.mijorus.smile`

**Comment by mijorus** [comment]
it's the old version 1.7 version

**Comment by RichardFevrier** [comment]
Okay so I did reproduce the bug when I uninstalled it and re-installed the latest version published on flathub.

**Comment by RichardFevrier** [comment]
> 

Yes it was just for the test

**Comment by mijorus** [comment]
I've found the issue, it has to do with the new "Run in the background" option.
Please expect a fix in the following hours

**Comment by RichardFevrier** [comment]
Effectively you can close this issue, after enabling it, it is now working again 🎉

**Comment by mijorus** [comment]
Well, it was supposed to work

**Comment by mijorus** [comment]
There are probably some issues with Gtk4 and/or python which I will report.

In the meanwhile, I made it work with a workaround.

@RichardFevrier could you please test this development build, with `Run in the background` OFF on your system?

Thank you

```
flatpak install --user https://dl.flathub.org/build-repo/2013/it.mijorus.smile.flatpakref
```

**Comment by RichardFevrier** [comment]
Sure!

**Comment by RichardFevrier** [comment]
Working perfectly with `Run in the background` disabled 👍️

**Comment by mijorus** [comment]
i'll release this patch later, thank you

**Comment by RichardFevrier** [comment]
Thank YOU 🙂

**Comment by RichardFevrier** [comment]
I have a bad news, it is not working after enabled and disable `Run in the background`

**Comment by mijorus** [comment]
lol

**Comment by mijorus** [comment]
could it be due to the fact that you have multiple versions installed?

**Comment by RichardFevrier** [comment]
Never mind it was just not working because I had the preference pane opened

**Comment by mijorus** [comment]
I will run some more tests, let me know..

Thank you

**Comment by RichardFevrier** [comment]
I think you did a great job!
The version from `flatpak install --user https://dl.flathub.org/build-repo/2013/it.mijorus.smile.flatpakref` is working like a charm.
I will wait the next flathub version to replace this one.

**Comment by mijorus** [comment]
The latest version was uploaded to flauthub.
It usually takes a few hours before it becomes available.

When you receive the update, you can safely remove the testing branch with the following command

```
flatpak remove it.mijorus.smile/x86_64/test
```

**Comment by Visual-Dawg** [comment]
I am on Wayland and copying still only works with 'Run in background'
