### ISSUE TITLE
Make picking the first found emoji faster

### ISSUE THREAD

**Issue by madx** [mijorus/smile#28]
Hello and thanks for the new version, the update to GTK4 really brings some fresh air and having it finally working better on Wayland is great!

I noticed that there is no easy way (or at least no documented one) to easily pick the first found emoji in the list through a keyboard action.

Having this would really make inputting emojis smoother!

**Comment by mijorus** [comment]
It's a great idea. This is coming out soon with version 2.0.5.

If you want to test this new version, you can do so with the following command

```
flatpak install --user https://dl.flathub.org/build-repo/2157/it.mijorus.smile.flatpakref
```

**Comment by mijorus** [comment]
Btw, sorry this needs explaining.

With version 2.0.5, you will be

**Comment by madx** [comment]
This is working great, I was able to test with the ArchLinux package which is already updated 😅 
Thanks a lot!
