### ISSUE TITLE
Show information about the hovered emoji

### ISSUE THREAD

**Issue by madx** [mijorus/smile#29]
There's currently no way to get information about the focused/hovered emoji such as the emoji name and aliases.

Adding this would help when learning the emoji names and make finding the ones you want faster.

**Comment by mijorus** [comment]
with version 2.0 you can now click with the middle button on the emoji to quickly open the custom tag manager, which also shows the name and the respective tags

**Comment by madx** [comment]
Oh wow I guess I missed that feature! My bad, I will close this issue then :) Thanks for the swift reply
