### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by RichardFevrier** [mijorus/smile#30]
Hi 🙂 after the last update on `Flathub` icons does not appear anymore.

![Screenshot from 2023-01-27 17-25-04](https://user-images.githubusercontent.com/5154754/215139706-c653c9d8-69f7-4e4d-a890-1af9d43f3fd6.png)

```
Smile - An emoji picker

          ID: it.mijorus.smile
         Ref: app/it.mijorus.smile/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 2.0.5
     License: GPL-3.0-or-later
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 16,1 MB
     Runtime: org.gnome.Platform/x86_64/43
         Sdk: org.gnome.Sdk/x86_64/43

      Commit: 3e4469a5d90b2c1a7a6f78321c127d262f3a0d6c27a2a32cb6e6321c7d3878f0
      Parent: 76014665024aa530f0a51e28dc421e6c432a8f58f5bbd5a24c5fd92061c313e1
     Subject: Update it.mijorus.smile.json (61a8c1b5)
        Date: 2023-01-26 23:15:04 +0000
```

**Comment by mijorus** [comment]
WTF!

**Comment by mijorus** [comment]
I mean... I have shipped broken updates in the past but this would have been too much

**Comment by samsch** [comment]
For future referencers, like myself an hour ago, here's a potential cause and solution:

I had previously manually installed noto color emoji and setup a config in `~/.config/fontconfig/fonts.conf` to setup emoji fonts for my system (Xubunto 22.04 LTS). At some point in the last few months (possibly February 2023 when the repo fonts-noto-color-emoji package was updated) a system update broke that configuration.

My solution was to remove/uninstall my existing manually installed noto color emoji and that font config, clear font cache `fc-cache -fv`, then install the ubuntu package: `sudo apt install fonts-noto-color-emoji`. This fixed the emoji issue and allowed emojis to continue to work in apps like mousepad.
