### ISSUE TITLE
Icon looks weird

### ISSUE THREAD

**Issue by gregorni** [mijorus/smile#37]
The current icon, from far away or on low-res screens, looks more like a not-perfectly-round smiley than a round-with-some-perspective smiley (if that makes any sense). I think a new icon should be designed, either with more contrast between top and side, or with a different shape altogether.

**Comment by gregorni** [comment]
I suggest asking in [#appicondesign](https://matrix.to/#/#appicondesign:gnome.org)

**Comment by mijorus** [comment]
Hi @gregorni , 
the icon was redesign a just couple of weeks ago.

Could you please share some technical details about your setup so I can try to replicate it?

Thanks


To be fair, I'm only using HI-Res display

**Comment by gregorni** [comment]
Well, I'm using Fedora 38 beta, but I actually just meant the icon found on the Flathub page and the Readme.

**Comment by mijorus** [comment]
sooo..... you are not the application icon in the app laucher?

Could it be due to compression?

**Comment by gregorni** [comment]
> sooo..... you are not the application icon in the app laucher?

No

> Could it be due to compression?

I was actually more thinking just the shape of the actual icon: I'm guessing the icon is a thin, but 3-dimensional, circular cylinder. However, the top-and-front perspective makes the cylinder look like a 2-dimnesional oval shape. 

One could also say the face looks like it has fat cheeks.
