### ISSUE TITLE
Ability to change the keyboard shortcuts

### ISSUE THREAD

**Issue by suda** [mijorus/smile#4]
Hi Lorenzo, I love this app! Nice and clean, exactly what's necessary for the job!
One thing I'm missing is the ability to set your own keyboard shortcuts. Unfortunately <kbd>Shift</kbd>+<kbd>Enter</kbd> in many apps is taken over by submit/new line.
I ended up setting a shortcut using Gnome Keyboard Settings:

![Screenshot from 2022-02-23 14-17-36](https://user-images.githubusercontent.com/25722/155327588-e1659c14-696f-45ca-9269-8a4e67285fd7.png)

But it would be nice to be able to do it within the app :)

**Comment by mijorus** [comment]
Hi, 
I didn't get it. 

Right now, I let the user create its own shortcut to launch the app, by providing the command.
