### ISSUE TITLE
Add option to increase the size of the emojis

### ISSUE THREAD

**Issue by marco4mp** [mijorus/smile#42]
Hi! 
An option to increase the size of the emojis would be great.
On my 14" laptop with 1920x1080 resolution the emojis look quite small. Although I can still see the emojis fine, a 2x size would be more comfortable. I also think it would be useful for people with certain vision problems.

Greetings!

**Comment by mijorus** [comment]
sounds reasonable to me👍

**Comment by mijorus** [comment]
WIP

**Comment by mijorus** [comment]
Version 2.2.0 adds an option to increase the font size of the emojis, it is released now.

Let me know if that helps

**Comment by marco4mp** [comment]
Thank you! The "giant" option is the one I personally find most comfortable.

**Comment by mijorus** [comment]
> Thank you! It works for me 👍️. The "giant" option is the one I personally find most comfortable.

Glad to here that! Btw are you sure that you are using display scaling correctly?

**Comment by marco4mp** [comment]
> Glad to here that! Btw are you sure that you are using display scaling correctly?

I use the default Gnome options, on a 1920x1080 14" screen, scaled to 100%.
I have attached a screenshot comparing the size of Smile and Gnome Characters.

![Captura desde 2023-04-18 17-25-40](https://user-images.githubusercontent.com/52709674/232910002-68e750b4-b9f5-48a8-bc9c-7ef3def3d4b0.png)
