### ISSUE TITLE
Support the GNOME search

### ISSUE THREAD

**Issue by 7system7** [mijorus/smile#43]
It would be great if somehow we can search with the GNOME global search without open the app first. :slightly_smiling_face:

**Comment by mijorus** [comment]
this sounds so cool! didn't even know it existed.

Looking into it

**Comment by ghassan0** [comment]
This would be great if implemented! This is especially helpful for touchscreen devices where creating a custom keyboard shortcut to open the app isn't an option. 

Afterwards, I'd be able to completely drop Gnome Characters for Smile.

**Comment by yochananmarqos** [comment]
@mijorus Check out GNOME Characters, one can already use GNOME Search to find emojis with it.

**Comment by mijorus** [comment]
Hi, 
I'm closing this as I think that this feature doesn't add much in terms of user experience and it is not worth the effort to develop it. I'm sorry
