### ISSUE TITLE
[Feature] Edit custom_tags.json inline

### ISSUE THREAD

**Issue by ghassan0** [mijorus/smile#45]
Hey, thanks for creating this app. I like having my config files synced between my different computers using a git repo and then symlinked into place. I'm trying to have my custom tags backed up and synced along with the rest of my configs. Unfortunately, I've noticed that whenever I add a new custom tag, the symlink to `custom_tags.json` gets replaced with a new file instead of being edited inline. I was wondering if there was an easy way to fix this.

**Comment by mijorus** [comment]
I could not find a way to do this, I'm sorry
