### ISSUE TITLE
cannot find vampire (or: missing emoji aliases)

### ISSUE THREAD

**Issue by igalic** [mijorus/smile#47]
when looking for vampire, all I'm finding in Smile is (vampire) bat:
![image](https://github.com/mijorus/smile/assets/497249/ebb84f41-45d5-46c6-af10-29849ada2415)

I reckon this is true for many things, but vampire is the most common thing I look for
(I'm just garlic intolerant, not really a vampire)

This is happening in: 2.3.0
Installed via Elementary "App Store"

**Comment by mijorus** [comment]
Hi @igalic, 
I am sorry, but if I start to accept any request for new tags, we end up with yet another project which is handling tags by hand without any logic of reusability for other projects; this is why I am using emojibase as source.

If you did not know, you can create custom tags in Smile (with Alt + T, check  the Shortcuts section in the app for more details), which should solve your issues.

Also, you can search for emojis: you can search for "🧛", and then create a custom tag.

Furthermore, I am working on a Backup/Restore feature which, together with #45, should make it easier to move your configuration around.

Thanks for the understanding.

**Comment by igalic** [comment]
emoji base has the right tags: https://github.com/search?q=repo%3Amilesj%2Femojibase%20vampire&type=code

so this isn't a feature request but a bug report

**Comment by mijorus** [comment]
fixed with 2.3.1

https://github.com/flathub/it.mijorus.smile/pull/29#issuecomment-1569835364
