### ISSUE TITLE
Emoji 15.0 support

### ISSUE THREAD

**Issue by iro-miya** [mijorus/smile#54]
Hiiii, first of, thank you for your work on Smile, it's very useful! 🩷

So far, Smile only lists emojis up to version 14.0 of Unicode. I was wondering if you had any plans to support [version 15.0](https://emojipedia.org/unicode-15.0/) which is now rather well supported, including by Noto, iOS, and Android.

Thanks!

**Comment by mijorus** [comment]
Added now, with version 2.7.0

**Comment by mijorus** [comment]
Btw Windows 11 still does not support Unicode 15

**Comment by iro-miya** [comment]
Clearly free software is the best :+1: thanks for the speedy patch 🩷

![image](https://github.com/mijorus/smile/assets/126985175/152ffca5-a3a2-4ee8-8582-002126f95a29)

Maybe it would be nice to only display emojis supported by the user's system, if you don't already do that, that way you don't have to make a call for when a new set of emojis is well-supported enough to be added.

By the way, [the next emojis](https://emojipedia.org/emoji-15.1/) are due for September 2023.
