### ISSUE TITLE
Keep the emoji picker open after inserting an emoji.

### ISSUE THREAD

**Issue by rago666** [mijorus/smile#55]
I know https://github.com/mijorus/smile/issues/5 & https://github.com/mijorus/smile/issues/24 exists. I am reopening as recently the app got a major UX update with **automatic emoji pasting.** Previously, when the app could only copy emoji it made perfect sense. But the app behaves similar to Windows's native emoji picker. In Windows, emoji picker remain open and user can input as many emoji as they want. One has to press esc or the close button to get to normal editiing mode. And in my opinion this is the correct UX behavior. 
IMO, Multi selection is not very intuitive for a casual user as one needs to simultaneously use both mouse and keyboard. I know  you can only use the keyboard but I think that is even less intuitive for a normal user.
Emoji's are heavily used by normal people in social media and normal people heavily relies on point & click. So, it would be really nice if you consider this. That's it have a great day.

**Comment by mijorus** [comment]
This feature is technically ready, but I think it requires some more work. Right now, the UX is not great, IMO
