### ISSUE TITLE
Copied icon display in serach field

### ISSUE THREAD

**Issue by gitalm** [mijorus/smile#59]
Thanks for the wonderful software,

I have a small bug with version 2.8.1
When i search an icon (image 1) and click on it, the windows diapears and i can paste it anywhere.
If i now reopen the window, the icon appears always in the search filed (image 2).
It would be more convenient, if the search field is empty, to search the next icon without emptying its content.

But it is a wonderful piece of software. Thanks

This happen under ubuntu with xfce.

![grafik](https://github.com/mijorus/smile/assets/7422149/104e75f4-44ef-458d-a36e-cdeab64aeb3b)

**Comment by mijorus** [comment]
Hi @gitalm, this should not happen as Smile is designed to clear the search bar when you quit the application.

Two questions:
- Are you using the auto-paste feature?
- Can you please run this command to install a beta version?

`flatpak install --user https://dl.flathub.org/build-repo/52010/it.mijorus.smile.flatpakref`
