### ISSUE TITLE
Smile is slow to open, laggy

### ISSUE THREAD

**Issue by evdcush** [mijorus/smile#64]
Thanks for your app; it's really great!

I've been using Smile for about 12 months now on 5 different machines (all running vanilla Focal).

I'm encountering an issue on a new machine I've not dealt with before.

Smile is **very slow to open/load**, taking about 35s from `flatpak run it.mijorus.smile` to the app appearing.
It is also **very slow and laggy** while running.
Attempting to change settings or resize the app window will freeze the app for about 15s.
Scrolling has huge latency.

I cannot figure out what the problem is.
Other flatpak apps launch and operate normally.

Only Smile is experiencing these performance issues.

It's unusable on my new machine.

How can I fix this?

---

For reference, I also get the following stack of warnings/error when I run the app:

```
$ flatpak run it.mijorus.smile
libEGL warning: DRI2: could not open /dev/dri/card0 (No such file or directory)
MESA: error: Failed to query drm device.
libGL error: glx: failed to create dri3 screen
libGL error: failed to load driver: iris
libGL error: failed to open /dev/dri/card0: No such file or directory
libGL error: failed to load driver: iris

** (process:2): WARNING **: 21:41:28.221: expected enumeration type void, but got PyGLibOptionArg instead

** (process:2): WARNING **: 21:41:28.221: expected enumeration type void, but got PyGLibOptionArg instead
```

**Comment by mijorus** [comment]
Hi,
35s sounds crazy to me, even on the most underpowered machine I have does not take that long.

Are you sure it's about Smile and not some background process going slowing things down?

**Comment by evdcush** [comment]
Thank you for your speedy response!

35s is crazy!

> Are you sure it's about Smile and not some background process going slowing things down?

**Smile is the only app that has this monstrously slow startup and laggy operation.**

The only thing remarkable about the host I am attempting to use Smile on (other than the 5 or so other machines with the same kernel, distro, DE, etc..) is that it is running on laptop with an Nvidia GPU (with nvidia drivers).

My desktops are all buntu with nvidia drivers, but I know discrete graphics cards on laptops can sometimes cause trouble.

Other than the discrete card and nvidia drivers, nothing is remarkable about my setup:

```
OS: Ubuntu 20.04 focal
Kernel: x86_64 Linux 5.15.0-88-generic
Packages: 2602
Shell: zsh 5.8
Resolution: 2560x1600
DE: GNOME 3.36.5
WM: Mutter
WM Theme: Adwaita
GTK Theme: Yaru [GTK2/3]
Icon Theme: Yaru
Disk: 254G / 483G (56%)
CPU: 11th Gen Intel Core i7-11850H @ 16x 4.8GHz [45.0°C]
GPU: NVIDIA GeForce RTX 3050 Ti Laptop GPU
RAM: 8186MiB / 31795MiB
```

Is there anything about Smile that attempts to utilize hardware acceleration in a manner different from other flatpak-based apps?

**Comment by evdcush** [comment]
I took a screenshot of my `htop` while I was scrolling Smile (since scrolling has performance issues).

![slow_smile](https://github.com/mijorus/smile/assets/28853935/51537acf-54c1-493d-baab-739a1689f900)

Is there any information or data I can provide that would help us debug this issue?

I noticed that Smile is using system python(?)

Could my python setup slow things down?

**Comment by evdcush** [comment]
I'm now experiencing this bug on a different machine and build.
Regrettably, it is unusable with this issue.

Machine specs:

```
OS: Ubuntu 22.04.3 LTS x86_64 
Host: 21AJS43900 ThinkPad T14 Gen 3 
Kernel: 6.2.0-37-generic 
Uptime: 34 mins 
Packages: 2634 (dpkg), 39 (flatpak) 
Shell: zsh 5.8.1 
Resolution: 2240x1400 
DE: GNOME 42.9 
WM: Mutter 
WM Theme: Adwaita 
Theme: Yaru [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: guake 
CPU: 12th Gen Intel i7-1270P (16) @ 4.800GHz 
GPU: Intel Alder Lake-P 
Memory: 4714MiB / 15650MiB 
```


Verbose run log:

```
flatpak run -v it.mijorus.smile
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/foobar/.local/share/flatpak
F: Opening user flatpak installation at path /home/foobar/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Skipping parental controls check for app/it.mijorus.smile/x86_64/stable since parental controls are disabled globally
F: Opening user flatpak installation at path /home/foobar/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/45/1d2947259cdada54ac757fb46f076d40b60451b0395d050cea45c23e7a80d997/files/lib32 does not exist
F: Cleaning up unused container id 1971460983
F: Cleaning up per-app-ID state for it.mijorus.smile
F: Allocated instance id 2158874989
F: Add defaults in dir /it/mijorus/smile/
F: Add locks in dir /it/mijorus/smile/
F: Disallowing network access
F: Allowing dri access
F: Allowing wayland access
F: Running '/usr/libexec/flatpak-bwrap --args 39 /usr/libexec/flatpak-dbus-proxy --args=41'
F: Running '/usr/libexec/flatpak-bwrap --args 39 smile'

** (process:2): WARNING **: 01:08:22.909: expected enumeration type void, but got PyGLibOptionArg instead

** (process:2): WARNING **: 01:08:22.909: expected enumeration type void, but got PyGLibOptionArg instead
```

**Comment by mijorus** [comment]
Hi,
has the situation improved somehow with the latest release?

**Comment by evdcush** [comment]
Hi @mijorus, thanks for the followup.

Unfortunately the latest release, `2.9.0`, did not fix the issue for me.

I included a screenshot of a verbose `run` if it helps.

![smile02](https://github.com/mijorus/smile/assets/28853935/64fe1f0e-2e0d-4e95-a100-936e96a55daf)

**Comment by chagai95** [comment]
I'm facing the same issue, very long time, is there a way to just keep it open in the background?

**Comment by Thalionquses** [comment]
I suddenly started to have the same problem and the app takes around 48 seconds to start and is very unresponsive.

Output:
```
david@zbook-firefly14-g7:~$ flatpak run -v it.mijorus.smile 
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/david/.local/share/flatpak
F: Opening user flatpak installation at path /home/david/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/david/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/45/a7e98d7b10776989dc22e866ce672c14d3db0a20c509fbbc6c960e3ed26d28e6/files/lib32 does not exist
F: Cleaning up unused container id 564991831
F: Cleaning up per-app-ID state for it.mijorus.smile
F: Allocated instance id 1161744852
F: Add defaults in dir /it/mijorus/smile/
F: Add locks in dir /it/mijorus/smile/
F: Disallowing network access
F: Allowing dri access
F: Allowing wayland access
F: Running '/usr/bin/bwrap --args 40 /usr/bin/xdg-dbus-proxy --args=42'
F: Running '/usr/bin/bwrap --args 40 smile'
david@zbook-firefly14-g7:~$
```

My system:
```
OS: Fedora 39
Gnome: 45.4
Wayland
CPU: i7-10610U
GPU: Intel iGPU
RAM: 32GB
```

**Comment by wada3n** [comment]
same to me!

**Comment by mijorus** [comment]
I'm looking into this

**Comment by mijorus** [comment]
Version 2.9.2 should improve the situation

**Comment by mijorus** [comment]
It takes less then 1.5s to open on my 6th gen i5 6500T now. I hope it works just as good for you

**Comment by Thalionquses** [comment]
The app opens now near instantly on my system. Thanks for looking into it and fixing the bug. 🙏

**Comment by mijorus** [comment]
Thanks for contributing with this bug report.

If you want to support my work, please consider a small donation.

https://ko-fi.com/mijorus

**Comment by Garbg** [comment]
I just installed Smile and I'm having this issue, it takes about 30 seconds to load, and it is super laggy and unresponsive. I have an intel core i9-10850k and a radeon rx 6600

**Comment by chagai95** [comment]
@Garbg what version do you have installed?

**Comment by chagai95** [comment]
@Garbg what's the newest version on flathub?

**Comment by evdcush** [comment]
Bug persists on a
fresh install of 22.04 (on host upgraded from 20.04 that previously had zero issue with Smile):

- `OS: Ubuntu 22.04.4 LTS; x86_64 6.5.0-27-generic`
- `Shell: zsh 5.8.1`
- `DE: GNOME 42.9`
- `GPU: nvidia-driver-550`

**Comment by evdcush** [comment]
Flatpak version (currently latest) `2.9.4`

![Screenshot from 2024-04-14 20-06-14](https://github.com/mijorus/smile/assets/28853935/9a43a3ae-8b31-4070-ba2e-457e4da88c5d)
