### ISSUE TITLE
A way to change default emoji font

### ISSUE THREAD

**Issue by vitordelucca** [mijorus/smile#65]
Is there a way to change the default emoji font? Right now it sticks on Noto-Emoji even if I change... Maybe a option to follow system's default emoji?

I wanted to use Segoe Emoji's...

**Comment by mijorus** [comment]
Hi, 
this feature currently is not planned.

The system font that you are currently using might or might not support all the emojis that Smile is currently supporting, which might result in broken placeholders.

Smile takes advantage of Flatpak's sandboxing to ensure that everyone can at lease see all the emojis correctly.
