### ISSUE TITLE
Customization: Default skintone sometimes does not load

### ISSUE THREAD

**Issue by evdcush** [mijorus/smile#67]
Thanks @mijorus for this awesome app!

I have the `Default skintone` Customization configured in my Smile app settings.

I've been encountering a bug where, sometimes, Smile launches without respecting the `Default skintone` customization, instead loading the app-default generic color (yellow).

- Ubuntu 20.04
- `5.15.0-88-generic`
- GNOME `3.36.5`
- Smile: Flatpak version `2.8.3`

I'm not sure how to reproduce this bug, so I'll close this issue.
Feel free to reopen it should other users report a similar bug.

**Comment by mijorus** [comment]
I'll keep this open to investigate

**Comment by mijorus** [comment]
The latest update should fix this issue

**Comment by mijorus** [comment]
Thanks for contributing with this bug report.

If you want to support my work, please consider a small donation.

https://ko-fi.com/mijorus
