### ISSUE TITLE
Flatpak just closes when clicking an emoji

### ISSUE THREAD

**Issue by evantaur** [mijorus/smile#76]
Running Debian 12/Sway, smile starts up normally but when you click an emoji it just closes, the emoji is not copied to the clipboard and there are no error reported on the commandline after running `flatpak run it.mijorus.smile && echo "No error"`

maybe there's something that prevents the clipboard to work under wayland session?

**Comment by mijorus** [comment]
Yeah, this is an error that keeps popping up

**Comment by mijorus** [comment]
Could you please install this test build and check if this has fixed the issue for you?
Please remember to quit Smile using the X button before installing the update

```
flatpak install --user https://dl.flathub.org/build-repo/90413/it.mijorus.smile.flatpakref
```

**Comment by evantaur** [comment]
well it doesn't close anymore but the clipboard is not functioning.

this happens when you click an emoji:
```
Traceback (most recent call last):
  File "/app/share/smile/smile/Picker.py", line 303, in handle_emoji_button_click
    self.copy_and_quit(widget)
  File "/app/share/smile/smile/Picker.py", line 622, in copy_and_quit
    subprocess.run(['wl-copy', copied_text])
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'wl-copy'
```
It seems you forgot to include wl-copy

**Comment by mijorus** [comment]
I did in that release, I'm sorry. I went on and published a new stable release all together (2.9.3), which should work as espected

**Comment by evantaur** [comment]
Confirmed working on the emoji getting copied to the clipboard, it still closes immediately after it does so, is this intended behavior? (If it is could you consider adding a "keep alive" toggle?)

Actually while testing I found out that if I turn the "minimize on exit" on it will stay open on sway because there's nothing to minimize it to other than scratchpad, so it's a bug and a feature.

**Comment by mijorus** [comment]
> Confirmed working on the emoji getting copied to the clipboard, it still closes immediately after it does so, is this intended behavior? (If it is could you consider adding a "keep alive" toggle?)

Right, the setting you might be looking for is "Mouse multi selection", which allows you to select multiple emojis by clicking.

**Comment by mijorus** [comment]
I think we can mark this issue as completed

**Comment by mijorus** [comment]
Thanks for contributing with this bug report.

If you want to support my work, please consider a small donation.

https://ko-fi.com/mijorus
