### ISSUE TITLE
Smile takes forever to open and is unresponsive.

### ISSUE THREAD

**Issue by Garbg** [mijorus/smile#77]
Opening smile takes about 30 seconds, and it is so unresponsive it is unsusable. I have an intel core i9-10850k CPUand an AMD Radeon RX 6600 GPU. Your other apps like gear lever work perfectly fine.

**Comment by Garbg** [comment]
When it's opening for some reason it uses 99% of my CPU.

**Comment by Garbg** [comment]
Maybe it's because I just installed it and it has to load stuff in for the first time?

**Comment by Garbg** [comment]
Right after I open it my CPU goes to 100% on one thread

**Comment by evdcush** [comment]
Related #64

**Comment by mijorus** [comment]
I honestly don't know how to debug this, I'm trying on every platform and configuration I possibly can, but Smile always runs just fine for me

**Comment by Garbg** [comment]
I am using opensuse tumbleweed. I might try reinstalling it.

**Comment by mijorus** [comment]
Realistically, the only thing that could slow it down is the rendering of the emoji list, but we are talking about a couple of hundred items at maximum, it shouldn't be a big problem

**Comment by mijorus** [comment]
Can we close this then?

**Comment by Garbg** [comment]
I don't know it fixed itself
