### ISSUE TITLE
What is the package name?

### ISSUE THREAD

**Issue by nexus-chris** [mijorus/smile#8]
I want to launch this with a custom shortcut, but I need to know the package name. I tried 'smile', but that didn't work. Running Fedora 35

**Comment by nexus-chris** [comment]
I did `flatpak list` and it shows the application id is `it.mijorus.smile`, but that doesn't work either to launch it

**Comment by nexus-chris** [comment]
The solution was to do `flatpak run it.mijorus.smile`, hopefully this will be useful to those installing the flatpak version

**Comment by mijorus** [comment]
Hi nexus,
The package name is available in the 'preferencies' of the app..

An introduction guide is in the work, will be coming soon.

![image](https://user-images.githubusercontent.com/39067225/158979855-170c55ff-e15c-4467-a63a-8dc27d3201f8.png)
