### ISSUE TITLE
Run in the background: Closing the window quits the app

### ISSUE THREAD

**Issue by Kekun** [mijorus/smile#91]
When an app is set to run in the background, closing its last window shouldn't quit the app. It works as intended when picking an emoji or pressing Escape, but not when clicking the window's close button.

I'm running 2.9.6 from Flathub on Fedora Silverblue 41.20241013.n.0.

**Comment by mijorus** [comment]
Hi, 
this is by design.

As the app is meant to be always running in the background, some users wanted a quick way to close the app without using the task manager.

If you simply want to hide it, press ESC on your keyboard

**Comment by Kekun** [comment]
That goes against what's done by all other apps, the fact the window can be closed via Escape doesn't mean closing the window the normal way (via its close button) should result in the app quiting when it's set to… not quite when closing the window.

I understand these users wanted that, but IMO this is the wrong way to do it. Maybe they could have some more explicit way to quit the app? Ctrl+Shift+Q or Ctrl+K (for kill) maybe?

To be fair that speaks for the lack of a design for background apps in the GNOME HIG: https://gitlab.gnome.org/Teams/Design/whiteboards/-/issues/237

**Comment by gwuen** [comment]
I also thought this was a bug and actually didn't figure out <kbd>Esc</kbd> is the way to keep the app running until looking at this issue.

I would be very happy to see <kbd>Ctrl</kbd> + <kbd>q</kbd> implemented as an alternative way to kill the app, as that's what all the other apps (and not only GNOME-y apps) I know of do :)

**Comment by gwuen** [comment]
@mijorus, may I ask again – would you be open to a PR that makes this configurable? Some feedback would be appreciated.

**Comment by mijorus** [comment]
> @mijorus, may I ask again – would you be open to a PR that makes this configurable? Some feedback would be appreciated.

Hi, what are you talking about if I can ask?
Do you basically want to keep the app running in the background when pressed ctrl q?

**Comment by gwuen** [comment]
> Do you basically want to keep the app running in the background when pressed ctrl q?

No, quite the opposite. When the application is configured to keep running in the background, I want this to apply to <kbd>Alt</kbd>+<kbd>F4</kbd> and pressing the close button, not just <kbd>Esc</kbd>. <kbd>Ctrl</kbd>+<kbd>q</kbd> could be a keybind to explicitly quit the app.

**Comment by gwuen** [comment]
We don't have to make this configurable either and this would simplify things, but you said some users specifically asked for the current default behavior.

**Comment by mijorus** [comment]
@gwuen wee need to give users a way to force close the app if they want to.

Usually, you close the app by pressing the X icon or Ctrl+Q, while Esc is a key that you usually associate with an application-specific behaviour

**Comment by gwuen** [comment]
> we need to give users a way to force close the app if they want to.

I agree, and that's what <kbd>Ctrl</kbd>+<kbd>q</kbd> should do.

> Usually, you close the app by pressing the X icon or Ctrl+Q

The way I understand and expect it: you close an individual *window* by pressing the X icon or <kbd>Alt</kbd>+<kbd>F4</kbd>, while <kbd>Ctrl</kbd>+<kbd>q</kbd> *quits the app* including its background services. Here's an incomplete list of apps that behave this way:

- [Chromium](https://www.chromium.org/Home/) (no <kbd>Ctrl</kbd>+<kbd>q</kbd>, but a dedicated “Exit” button)
- [Discord](https://discord.com/download)
- [Easy Effects](https://github.com/wwmm/easyeffects)
- [Eyedropper](https://apps.gnome.org//Eyedropper/)
- [GNOME Files](https://apps.gnome.org/Nautilus/) (<kbd>Ctrl</kbd>+<kbd>q</kbd> closes all windows; the background service always keeps running)
- [Firefox](https://www.firefox.com/en-US/) (<kbd>Ctrl</kbd>+<kbd>q</kbd> closes all windows, but there's no background service)
- [Forge Sparks](https://apps.gnome.org/ForgeSparks/)
- [Packet](https://github.com/nozwock/packet)
- [Signal Desktop](https://github.com/signalapp/signal-desktop)
- [Solaar](https://github.com/pwr-Solaar/Solaar) (no <kbd>Ctrl</kbd>+<kbd>q</kbd>, but a dedicated “Quit” button)
- [Telegram Desktop](https://github.com/telegramdesktop/tdesktop)

It would be hard to find counter-examples. In fact, Smile is the only app with a background service I can think of that fully quits when pressing <kbd>Alt</kbd>+<kbd>F4</kbd>.

According to the [GNOME HIG](https://developer.gnome.org/hig/reference/keyboard.html), <kbd>Ctrl</kbd>+<kbd>q</kbd> “closes the app, including all its windows”, while <kbd>Ctrl</kbd>+<kbd>w</kbd> and <kbd>Alt</kbd>+<kbd>F4</kbd> “close the current window [or tab]”. The latter is a system shortcut handled by Mutter, of course.

As @Kekun already pointed out, there's unfortunately a lack of GNOME guidelines specifically for background apps, but as it stands, Smile is the clear outlier with its current behavior, not only among the apps made for GNOME.
