### ISSUE TITLE
GNOME Runtime 45 is no longer being supported (EOL)

### ISSUE THREAD

**Issue by NotoriousNico** [mijorus/smile#92]
When running `flatpak update`, I get the following info message:

```
Info: runtime org.gnome.Platform branch 45 is end-of-life, with reason:
   The GNOME 45 runtime is no longer supported as of September 18, 2024. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   it.mijorus.smile
```

While Smile is running fine, could you please migrate to a newer GNOME runtime, so that this message goes away?

**Comment by n3thshan** [comment]
I second this but for a different reason. With GNOME 47's flagship feature of accent colors, the old 45 runtime does not respect the accent colour that i have selected. Updating to the 47 runtime will help alleviate this issue. Please consider this!

**Comment by mijorus** [comment]
I've just pushed a new update which includes the latest gnome platform and uses the system accent colors 🚀

**Comment by mijorus** [comment]
Thanks for contributing with this bug report.

If you want to support my work, please consider a small donation.

https://ko-fi.com/mijorus

**Comment by NotoriousNico** [comment]
@mijorus Sorry to bother you again, but can you please check the runtime again?
According to Warehouse, you are using GNOME Application Version Platform 46, and I also don't see my system's accent color when using Smile.

![image](https://github.com/user-attachments/assets/acd17473-a681-4a8d-9c7f-cb7516177eaa)

![image](https://github.com/user-attachments/assets/9aa5c40a-eccf-48bc-a3a3-10dc366a207b)
_The colors should be orange instead of blue._


I'm using Smile 2.10.0, that is the latest version, right?

**Comment by mijorus** [comment]
My bad, I'm pushing an update now

**Comment by NotoriousNico** [comment]
No worries, thank you for the very quick reply!

**Comment by Malix-Labs** [comment]
@mijorus has the updated been successfully pushed ?

It still shows 2.10.0 in flathub
