### ISSUE TITLE
Flatpak ver 2.10.0 is not using gnome 47 runtime. Instead its using 46. 

### ISSUE THREAD

**Issue by n3thshan** [mijorus/smile#95]
I noticed this with the accent colors not being applied but after looking at warehouse details it says its using 46. 

![image](https://github.com/user-attachments/assets/07f68907-3831-4ffc-89b0-a223890b93f5)

**Comment by NotoriousNico** [comment]
It'll be fixed soon, I've reported the same thing:

https://github.com/mijorus/smile/issues/92#issuecomment-2475657138

#92

**Comment by mijorus** [comment]
just pushed an update, sorry for that

**Comment by NotoriousNico** [comment]
@mijorus Sorry to bother you again, but has the update been pushed successfully? 2.10.0 still seems to be the latest version on Flathub.

Also, could you please take a look at this issue, in case you missed it?
#96

**Comment by mijorus** [comment]
@NotoriousNico yes, the update was pushed some days ago.

```
~ » flatpak info it.mijorus.smile                                                                                                                                                                                                              09:11:00

Lorenzo Paderi - An emoji picker

          ID: it.mijorus.smile
         Ref: app/it.mijorus.smile/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 2.10.0
     License: GPL-3.0-or-later
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 7.6 MB
     Runtime: org.gnome.Platform/x86_64/47
         Sdk: org.gnome.Sdk/x86_64/47

      Commit: 9edb6a0d54c8a9a4200bf134aaef7bdb613a4c73ab7b0b7a6cc8fcf5a286b954
      Parent: 2430a6ffbd5fe4159d9bcd1c2039383a40e9fab7e01619b9bc3f297561c04693
     Subject: Update it.mijorus.smile.json (ea64e66b)
        Date: 2024-11-17 20:30:06 +0000

```

**Comment by NotoriousNico** [comment]
@mijorus Thank you for that, so the version number of Smile didn't change, I wasn't aware of that.
I just checked Warehouse, and it's showing GNOME Application Platform version 47 now.

Issue #96 also seems to have been resolved by the new update. 👍️

**Comment by mijorus** [comment]
Thanks for contributing with this bug report.

If you want to support my work, please consider a small donation.

https://ko-fi.com/mijorus
