### ISSUE TITLE
Highlighted outline does not appear for emoji when navigating by keyboard

### ISSUE THREAD

**Issue by jessicarod7** [mijorus/smile#96]
When navigating emoji by keyboard, there is no highlight or outline around each emoji, so I can't tell which emoji is currently focused.

[Screencast From 2024-11-14 09-32-00.webm](https://github.com/user-attachments/assets/df94af10-6ab6-41d4-b8fd-39cbfcb8ff33)

Specs:
- OS: Fedora 41 (kernel 6.11.5-300.fc41.x86_64)
- Desktop environment: GNOME 47.1 (Mutter)
- App version: 2.10.0 (Flathub)
- GNOME extension installed: Yes

**Comment by NotoriousNico** [comment]
I have the exact same issue, except that I'm on Ubuntu 24.10.
There's also no more an indicator for the different Emoji categories on the bottom bar.


https://github.com/user-attachments/assets/c4b73018-814e-422c-b7b4-b4cd34bdbdd6

**Comment by NotoriousNico** [comment]
This issue seems to have been resolved with the latest update. Smile is still on version 2.10.0, but it's now correctly using GNOME Application platform version 47, which seems to have fixed the issue.

**Comment by jessicarod7** [comment]
Thanks for the heads up @NotoriousNico. Looks like the flatpak was fixed with a version re-release in flathub/it.mijorus.smile#69, closing this issue.

**Comment by mijorus** [comment]
Exactly, the update to the lastest runtime should have fixed this issue
